---
apiVersion: v2
name: istio-ratelimit-operator
description: Istio ratelimit operator provide an easy way to configure Global or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter versioning!
version: 2.11.0
appVersion: 2.11.0
type: application
home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator

maintainers:
- name: Zufar Dhiyaulhaq
  email: zufardhiyaulhaq@gmail.com
  url: https://zufardhiyaulhaq.com
