apiVersion: v1
entries:
  istio-ratelimit-operator:
  - apiVersion: v2
    appVersion: 2.7.0
    created: "2022-10-22T17:53:28.712647+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 65bf22ecc44d42804f007d35358aa34a8e558e8095d8269ba1672b31167a9ac2
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.7.0.tgz
    version: 2.7.0
  - apiVersion: v2
    appVersion: 2.6.1
    created: "2022-10-22T17:53:28.710944+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 53de7f1b8bbab18e4c630c45ba11987aaf9eb0a373bb663a226891063437c998
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.6.1.tgz
    version: 2.6.1
  - apiVersion: v2
    appVersion: 2.6.0
    created: "2022-10-22T17:53:28.709359+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: f68515c8b7a591df5423775a4e41449f4e4131fc329f52be41764c00824643e1
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.6.0.tgz
    version: 2.6.0
  - apiVersion: v2
    appVersion: 2.5.1
    created: "2022-10-22T17:53:28.707906+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: a39c2cbe61ac2f474750d787732a21cf2c3ec8bbce3cc3cd17bcfafd5a559eb9
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.5.1.tgz
    version: 2.5.1
  - apiVersion: v2
    appVersion: 2.5.0
    created: "2022-10-22T17:53:28.706529+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 64dda55b4a8ec23037152f2c60861803a806eb66ed6a66f13927f18c94ac6a84
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.5.0.tgz
    version: 2.5.0
  - apiVersion: v2
    appVersion: 2.4.0
    created: "2022-10-22T17:53:28.705207+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 08668539d33ca54907a6836a60bbc30cb91cc8dee7ba870f97f73e7dc2b69931
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v2
    appVersion: 2.3.0
    created: "2022-10-22T17:53:28.703987+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: ac0e11ecdeffa4fe656c17f3588d1880391477d9af56ce7165d3e6237ee2a170
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    appVersion: 2.2.0
    created: "2022-10-22T17:53:28.702683+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: a2979dd17de57397f8b21b8c8e91ec7024d61d9e27ebfe6329f2461dbf00daa4
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2022-10-22T17:53:28.70143+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 8e2589c35c4cdae7e1ae4c36d63927d1643f12c935eed81a1a8870f5b8472bbc
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-10-22T17:53:28.700219+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 4950de5d1f4ef8b304a21938d317b9abc2380cf41143fd9b9a8ebfcd073ea273
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-10-22T17:53:28.698982+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: a25e113e0de29a78de29262f5043a9db260eab8287f9a1facd732ba764da7d6a
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-1.0.0.tgz
    version: 1.0.0
generated: "2022-10-22T17:53:28.697613+07:00"
