apiVersion: v1
entries:
  istio-ratelimit-operator:
  - apiVersion: v2
    appVersion: 2.11.1
    created: "2023-10-12T11:33:27.214195+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 545c038dcbf44a7b06b099245976f6aa6b394d29cd40e2b8205a6c1f2c016f66
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.11.1.tgz
    version: 2.11.1
  - apiVersion: v2
    appVersion: 2.11.0
    created: "2023-10-12T11:33:27.213107+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: a97abe7189adf195fbadec05b7389921b2f63d978c4b763c6138a2ef268faf68
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.11.0.tgz
    version: 2.11.0
  - apiVersion: v2
    appVersion: 2.10.2
    created: "2023-10-12T11:33:27.211698+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: eecf1ed4488bbefb3059e9681ad4116d66d84656b488dcf5d23f64e21a599574
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.10.2.tgz
    version: 2.10.2
  - apiVersion: v2
    appVersion: 2.10.1
    created: "2023-10-12T11:33:27.209978+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: d2a9784895d56a91bdd98eec0249e96faead717c4a01f562056bb6cdadc005ac
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.10.1.tgz
    version: 2.10.1
  - apiVersion: v2
    appVersion: 2.10.0
    created: "2023-10-12T11:33:27.207524+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 7baae59bbb246bbc6fd9991b00b947ab89892cef9666508febdd0a3f1ab28c2b
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.10.0.tgz
    version: 2.10.0
  - apiVersion: v2
    appVersion: 2.10.0-rc.2
    created: "2023-10-12T11:33:27.205706+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 4f666b51a93210124576b0df1ba239c98d7d8f01f67cf8ac24664bc36deb6dac
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.10.0-rc.2.tgz
    version: 2.10.0-rc.2
  - apiVersion: v2
    appVersion: 2.10.0-rc.1
    created: "2023-10-12T11:33:27.204007+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: e4c7595410f87c56975f493f61634430e1aa59f07ac280f6d8bee42a3e6b5ee0
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.10.0-rc.1.tgz
    version: 2.10.0-rc.1
  - apiVersion: v2
    appVersion: 2.10.0-rc.0
    created: "2023-10-12T11:33:27.202373+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 318ecace22f81d2e6580d9e3e0e5cad0cacc38204f64c203d35550a4b8899b5a
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.10.0-rc.0.tgz
    version: 2.10.0-rc.0
  - apiVersion: v2
    appVersion: 2.9.0
    created: "2023-10-12T11:33:27.231498+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: a835be3fb0083c593b03a4d2e870ca01c2b8c32e945603518c4047358e10a5bf
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.9.0.tgz
    version: 2.9.0
  - apiVersion: v2
    appVersion: 2.8.0
    created: "2023-10-12T11:33:27.230039+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 9fe338e814ed013dbbb53db82556d177ad5b98c6fd5274ee62ed98ac3cdbf8ed
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.8.0.tgz
    version: 2.8.0
  - apiVersion: v2
    appVersion: 2.7.0
    created: "2023-10-12T11:33:27.227722+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: b59876b445554a2c07fa0e85d0576079822e1cf19bd45e1e179bcf472011f116
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.7.0.tgz
    version: 2.7.0
  - apiVersion: v2
    appVersion: 2.6.1
    created: "2023-10-12T11:33:27.226157+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 53de7f1b8bbab18e4c630c45ba11987aaf9eb0a373bb663a226891063437c998
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.6.1.tgz
    version: 2.6.1
  - apiVersion: v2
    appVersion: 2.6.0
    created: "2023-10-12T11:33:27.224704+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: f68515c8b7a591df5423775a4e41449f4e4131fc329f52be41764c00824643e1
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.6.0.tgz
    version: 2.6.0
  - apiVersion: v2
    appVersion: 2.5.1
    created: "2023-10-12T11:33:27.223239+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: a39c2cbe61ac2f474750d787732a21cf2c3ec8bbce3cc3cd17bcfafd5a559eb9
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.5.1.tgz
    version: 2.5.1
  - apiVersion: v2
    appVersion: 2.5.0
    created: "2023-10-12T11:33:27.221705+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 64dda55b4a8ec23037152f2c60861803a806eb66ed6a66f13927f18c94ac6a84
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.5.0.tgz
    version: 2.5.0
  - apiVersion: v2
    appVersion: 2.4.0
    created: "2023-10-12T11:33:27.220027+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 08668539d33ca54907a6836a60bbc30cb91cc8dee7ba870f97f73e7dc2b69931
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v2
    appVersion: 2.3.0
    created: "2023-10-12T11:33:27.217923+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: ac0e11ecdeffa4fe656c17f3588d1880391477d9af56ce7165d3e6237ee2a170
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    appVersion: 2.2.0
    created: "2023-10-12T11:33:27.215981+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: a2979dd17de57397f8b21b8c8e91ec7024d61d9e27ebfe6329f2461dbf00daa4
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2023-10-12T11:33:27.200851+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 8e2589c35c4cdae7e1ae4c36d63927d1643f12c935eed81a1a8870f5b8472bbc
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2023-10-12T11:33:27.199318+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 4950de5d1f4ef8b304a21938d317b9abc2380cf41143fd9b9a8ebfcd073ea273
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-10-12T11:33:27.196349+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: a25e113e0de29a78de29262f5043a9db260eab8287f9a1facd732ba764da7d6a
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-1.0.0.tgz
    version: 1.0.0
generated: "2023-10-12T11:33:27.194592+07:00"
